version: "3"

services:

  postgres:
    restart: always
    image: postgres:11-alpine
    container_name: postgres_
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ${PWD}/docker/dbdata/pgdata:/var/lib/postgresql
    networks:
      - backend

  redis:
    build: ${PWD}/docker/redis
    container_name: redis_
    volumes:
      - ${PWD}/docker/dbdata/redis:/data
    ports:
      - "6379:6379"
    networks:
      - backend



networks:
    backend:
        driver: "bridge"
