// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Documents string
	Links     string
	Messages  string
	Projects  string
	Users     string
}{
	Documents: "documents",
	Links:     "links",
	Messages:  "messages",
	Projects:  "projects",
	Users:     "users",
}
